### ISSUE TITLE
UnknownError - sqlite3.oo1.OpfsDb is not a constructor

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu#147]
Why?

**Comment by steida** [comment]
You have to add **COOP and COEP HTTP Headers** as described in https://sqlite.org/wasm/doc/trunk/persistence.md#coop-coep

In Next.js, add `async headers`:

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,

  // ADD THIS:
  async headers() {
    return [
      {
        source: "/(.*?)",
        headers: [
          {
            key: "cross-origin-embedder-policy",
            value: "require-corp",
          },
          {
            key: "cross-origin-opener-policy",
            value: "same-origin",
          },
        ],
      },
    ];
  },
};

module.exports = nextConfig;
```

**Comment by FilipChalupa** [comment]
Is there any recommended way to force `localStorage` instead of `opfs` in all browsers? I would love to try Evolu but I'm not able to get it working with `opfs` in our private pnpm monorepo.

Patching `Browser.js` with `false` on line 19 to force `localStorage` works for me but seems very dirty.

![](https://github.com/evoluhq/evolu/assets/1045362/33e1d287-6356-444c-ab5a-021db5ffe8ef)

-----------------

For `opfs` I've tried setting `cross-origin-*policy` headers in `next-config.js`, adding `"type": "module"` to `package.json`, copypasting your `examples/nextjs/tsconfig.json`. All without any luck. I'm still getting the `sqlite3.oo1.OpfsDb is not a constructor` in both Chrome (MS Edge) and Firefox.

![](https://github.com/evoluhq/evolu/assets/1045362/11f146b7-d5db-4878-a6cc-bd56b3904192)

![](https://github.com/evoluhq/evolu/assets/1045362/dec68091-3974-4ec6-bae0-2eb3ac5cbf2f)

**Comment by FilipChalupa** [comment]
The problem is that `source: "/(.*?)"` is not matching root url `/` and my app runs under `/`. 😅

#### Solution:

```js
const headers = [
	{
		key: 'cross-origin-embedder-policy',
		value: 'require-corp',
	},
	{
		key: 'cross-origin-opener-policy',
		value: 'same-origin',
	},
]

const nextConfig = {
  // ADD THIS:
  async headers() {
  	return [
  		{
  			source: '/',
  			headers,
  		},
  		{
  			source: '/(.*?)',
  			headers,
  		},
  	]
  },
};
```
