### ISSUE TITLE
Opt-out reload when calling evolu.resetOwner()

### ISSUE THREAD

**Issue by needim** [evoluhq/evolu#413]
I like to create a different UX when users tries to reset his account.

Proposal: `evolu.resetOwner({reload: false})`

**Comment by ananthakumaran** [comment]
I have faced similar UX issues when trying to implement a data reset feature. My app also needs multiple Evolu db instances (though one is active at any point in time), so making sure the resetOwner is not called on the wrong db was a bit hard to implement.

Since Evolu now has proper multi-db support, would it be possible to provide a normal Create, Delete, and Reset interface? There is no way to create a DB instance with a predefined mnemonic. On a new device, the app has to do a resetOwner even though it knows the mnemonic in advance.

**Comment by steida** [comment]
@ananthakumaran Good idea. Feel free to suggest an API for that.

**Comment by ananthakumaran** [comment]
Adding a mnemonic to `createEvolu` would solve the new device setup problem without an extra page reload.

```ts
return createEvolu(Database, {
    name: id,
    reloadUrl: '/',
    syncUrl: config.syncUrl,
    mnemonic: mnemonic
  });
```

Speaking of mnemonic, there is no straightforward way to make a new one using the public API. I use the below function to generate one.

```ts
import { Bip39Live } from '@evolu/common-web/dist/PlatformLive';
import { makeOwner } from '@evolu/common';

export async function newOwner() {
  return await Effect.runPromise(Effect.provide(makeOwner(), Bip39Live));
}
```

This along with the ability to not reload the page on `db.restoreOwner(mnemonic, {reload: false})` and `db.resetOwner({reload: false})` would solve all my UX issues.

**Comment by steida** [comment]
@ananthakumaran I'm working on that.

**Comment by ananthakumaran** [comment]
@steida 

I am testing it out and facing one issue. The `const owner = useOwner();` hook is not firing after calling

```ts
db.restoreOwner(mnemonic, {
  reload: false,
})
```

I am assuming this was working earlier due to the page reload on any owner change? I only see one call to `ownerStore.setState` on db initialization.

**Comment by steida** [comment]
@ananthakumaran Yep, you are right. Given that a user may have multiple tabs open, I'm trying to figure out what the correct approach is. Tabs should be reloaded anyway, IMHO. Otherwise, we would have to propagate user changes to all tabs.

**Comment by needim** [comment]
Tested and works well for me, thanks.
