### ISSUE TITLE
Add React Native support

### ISSUE THREAD

**Issue by steida** [evoluhq/evolu#86]
Sqlite for React Native and https://github.com/craftzdog/react-native-aes-gcm-crypto or similar for symmetric encryption.

**Comment by steida** [comment]
https://swr.vercel.app/docs/advanced/react-native

**Comment by gigq** [comment]
Just a heads up I tried adding Evolu to a react native project I have (I know support isn't officially there yet, but wanted to see if I could get started with it). I think you are going to run into issues with kysely as it's not currently supporting react native due to this issue:

https://github.com/kysely-org/kysely/issues/67

**Comment by steida** [comment]
@gigq It looks like this is all we need to support Kysely in React Native.

```js
// babel.config.js
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [['@babel/plugin-transform-private-methods', {loose: true}]],
};
```

**Comment by steida** [comment]
Done.
